[changelog]
header = ""
body = """
## What's Changed
{% for commit in commits %}\
* {{ commit.message | split(pat="\n") | first | trim }} by @{{ commit.remote.username | default(value=commit.author.name) }} in https://github.com/jamezrin/solrj-dobby/commit/{{ commit.id }}
{% endfor %}
**Full Changelog**: https://github.com/jamezrin/solrj-dobby/compare/{{ previous.version }}...{{ version }}
"""
trim = false

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
    { message = "^chore\\(release\\)", skip = true },
    { message = "^Merge pull request", skip = true },
    { message = "^Merge branch", skip = true },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"

[remote.github]
owner = "jamezrin"
repo = "solrj-dobby"
