[versions]
solrj9 = "9.10.1"
solrj10 = "10.0.0"
junit = "6.1.3"
spotless = "8.3.0"
maven-publish = "0.37.0"
google-java-format = "1.27.0"
testcontainers = "2.0.5"

[libraries]
solrj9 = { module = "org.apache.solr:solr-solrj", version.ref = "solrj9" }
solrj10 = { module = "org.apache.solr:solr-solrj", version.ref = "solrj10" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
# Versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-solr = { module = "org.testcontainers:testcontainers-solr", version.ref = "testcontainers" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
